### ISSUE TITLE
fzf/fd not found when installed via MacPorts instead of Brew

### ISSUE THREAD

**Issue by jy-gh** [yohasebe/fzf-alfred-workflow#1]
I have both `fzf` and `fd` installed via [MacPorts](https://www.macports.org/):

```
$ type fzf
fzf is /opt/local/bin/fzf

$ which fzf
/opt/local/bin/fzf

$ command -v fzf
/opt/local/bin/fzf
```
As you can see, [MacPorts](https://www.macports.org/) installs these binaries in the `/opt/local` tree. The workflow does not detect them.

I use `zsh`, and my `$PATH` is set in my `.zshrc` file, including `/opt/local/bin`.

**Comment by yohasebe** [comment]
Sorry for the late response! 

One solution is installing the workflow from Alfred Gallery, which automatically installs the required dependencies. Alternatively, you can set the paths for fzf and fd in the workflow’s `Environment Variables` by creating variables named `fzf_path` and `fd_path` and setting their values to the appropriate paths.

I hope this helps!

**Comment by jy-gh** [comment]
Thank you for responding. 

I believe that installing the workflow from the Alfred Gallery uses `brew`, does it not? If it does, I don't want to do that. I don't like `brew`, partly because I think it's kind of a hack and partly because I think it's a security hole.

As far as creating `fzf_path` and `fd_path` variables, that didn't seem to work for me. I have a screenshot--see below--but I did try using **both** the absolute path to both binaries as shown in the screenshot, but also just the directories (that is, `/opt/local/bin` instead of, say, `/opt/local/bin/fzf`.) In both cases I still get the large text display of *fzf is not installed*. (I use `fzf` and `fd` all the time from the shell, from vim, and from a workflow, so I'm certain they're installed.)

Thanks!

![fzf_env_vars](https://github.com/yohasebe/fzf-alfred-workflow/assets/22357499/cd338069-c1ba-49a8-9b00-fb4cebef66f7)

**Comment by yohasebe** [comment]
Sorry for my confusion. I'm happy to inform you that the problem has been fixed in the latest version 1.5.1 of fzf-alfred-workflow. The environment variables `fzf_path` and `fd_path` should now be properly reflected when set. Let me know if it is not the case.

**Comment by jy-gh** [comment]
I'm still having a bit of difficulty (and I did download 1.5.1, which the workflow displays in the workflow pane).

I have tried setting `fd_path` and `fzf_path` to `/opt/local/bin` as well as to `/opt/local/bin/fd` and `/opt/local/bin/fzf`, respectively, but I don't get results either way. (Nor do I get the large text error message **fzf is not installed message** in either case.) Just to clarify, do I set the variables like this:

```
fd_path    `/opt/local/bin`
fzf_path   `/opt/local/bin`
```

or this:

```
fd_path   `/opt/local/bin/fd`
fzf_path  `/opt/local/bin/fzf`
```

Here's a sample run showing the Debug output when giving the workflow the input `Desktop` first, and then (using a file that I know exists in my `$HOME` filesystem) the input `example.py`. In both cases I don't get any results.

```
[20:52:47.479] fzf-alfred-workfow[Keyword] Processing complete
[20:52:47.489] fzf-alfred-workfow[Keyword] Passing output 'Desktop' to Arg and Vars
[20:52:47.490] fzf-alfred-workfow[Arg and Vars] Processing complete
[20:52:47.491] fzf-alfred-workfow[Arg and Vars] Passing output 'Desktop' to Junction
[20:52:47.492] fzf-alfred-workfow[Junction] Processing complete
[20:52:47.493] fzf-alfred-workfow[Junction] Passing output 'Desktop' to Transform
[20:52:47.494] fzf-alfred-workfow[Transform] Processing complete
[20:52:47.494] fzf-alfred-workfow[Transform] Passing output 'Desktop' to Script Filter
[20:52:47.558] fzf-alfred-workfow[Script Filter] Queuing argument 'Desktop'
[20:52:58.566] fzf-alfred-workfow[Keyword] Processing complete
[20:52:58.579] fzf-alfred-workfow[Keyword] Passing output 'example.py' to Arg and Vars
[20:52:58.580] fzf-alfred-workfow[Arg and Vars] Processing complete
[20:52:58.580] fzf-alfred-workfow[Arg and Vars] Passing output 'example.py' to Junction
[20:52:58.581] fzf-alfred-workfow[Junction] Processing complete
[20:52:58.582] fzf-alfred-workfow[Junction] Passing output 'example.py' to Transform
[20:52:58.584] fzf-alfred-workfow[Transform] Processing complete
[20:52:58.585] fzf-alfred-workfow[Transform] Passing output 'example.py' to Script Filter
[20:52:58.628] fzf-alfred-workfow[Script Filter] Queuing argument 'example.py'
```

**Comment by yohasebe** [comment]
Please double-check that `fzf` and `fd` are properly installed and that their paths are correct. The latest version (1.5.1) does not check the availability of these commands, which is why you do not see the large text message anymore. However, it’s crucial that `fzf` and `fd` are accessible on the **system default** `zsh`, which the workflow uses.

The workflow assumes that the values for `fzf_path` and `fd_path` include the path to the executable files. Therefore, the second path notation you tried is the correct one. If these are set up correctly, you should get the expected results.

Another thing to check is the environment variable Search Path(s). By default, the home directory (`~`) is set, but on recent Macs, the save destinations for cloud storage services like Dropbox, OneDrive, and Google Drive are under `~/Library/CloudStorage/`. fzf-alfred-workflow avoids searching subdirectories named `Library` due to performance concerns. Therefore, to search folders like Dropbox, you need to explicitly specify the path like `~/Dropbox` or `~/Library/CloudStorage/Dropbox`.

**Comment by typkrft** [comment]
I am having similar issues. Fzf and fd are installed at `/etc/profiles/per-user/brandon/bin/fzf` and `/etc/profiles/per-user/brandon/bin/fd`. `fzf_path` and `fd_path` are set appropriately. The search path is `~`.


When a search is made for `code`, which is located at `~/code` it returns nothing. 
```
06:14:03.597] Logging Started...
[06:14:08.912] fzf-alfred-workfow[Keyword] Processing complete
[06:14:08.917] fzf-alfred-workfow[Keyword] Passing output 'code' to Arg and Vars
[06:14:08.918] fzf-alfred-workfow[Arg and Vars] Processing complete
[06:14:08.918] fzf-alfred-workfow[Arg and Vars] Passing output 'code' to Junction
[06:14:08.919] fzf-alfred-workfow[Junction] Processing complete
[06:14:08.919] fzf-alfred-workfow[Junction] Passing output 'code' to Transform
[06:14:08.919] fzf-alfred-workfow[Transform] Processing complete
[06:14:08.920] fzf-alfred-workfow[Transform] Passing output 'code' to Script Filter
[06:14:08.923] fzf-alfred-workfow[Script Filter] Queuing argument 'code'
[06:14:09.068] fzf-alfred-workfow[Script Filter] Script with argv 'code' finished
[06:14:09.079] fzf-alfred-workfow[Script Filter] {"items":[{"title":"No results found","valid":false}]}
```

**Comment by yohasebe** [comment]
Based on the log, it appears that fzf and fd are being recognized correctly. If they were not, the log would have displayed an error indicating that one or both of the commands could not be found.

Could you please try setting the search path to ~/code instead of just ~/, and then check if a search still returns an empty result? This might help me locate the cause of the problem.

**Comment by typkrft** [comment]
Setting the search path to `~/code` or `/Users/brandon/code` both return no results. Running fzf from the command line does work as expected for results within `~/code`

**Comment by yohasebe** [comment]
I don’t think zsh is related to the issue. However, since you’re using nix, which I’m not familiar with, it might be worth investigating if that’s causing the problem.

Could you try opening the workflow’s preferences and see what happens if you manually set the `fzf_path` and `fd_path` in the Ruby code, instead of relying on the environment variables?

Please click on the Script Filter element "FZF Search" and modify the code inside:

<img width="1139" alt="image" src="https://github.com/yohasebe/fzf-alfred-workflow/assets/18207/eaf452e8-34b2-47fe-afef-fe8222c37415">

```
# frozen_string_literal: true

require "json"
require "time"
require "fileutils"

history_file = File.expand_path "#{ENV['alfred_workflow_data']}/fzf-search-history.txt"
max_search_history = ENV["max_search_history"].to_i

def prepend_line_to_file(file_path, line_to_prepend, max_search)
  dirname = File.dirname(file_path)
  unless File.directory?(dirname)
    FileUtils.mkdir_p(dirname)
  end

  file_contents = File.readlines(file_path) if File.exist?(file_path)
  file_contents = [] unless file_contents

  if max_search <= 0
    file_contents = []
  elsif file_contents.size >= max_search
    file_contents = file_contents[0...(max_search - 1)]
    file_contents.unshift line_to_prepend
  else
    file_contents.unshift line_to_prepend
  end

  File.open(file_path, "w") do |file|
    file.puts(file_contents) if file_contents
  end
end

###############################################################
# let's see what happens if fd_path and fzf_path are hard coded

# fd_path       = ENV["fd_path"]     || `which fd`.strip
# fzf_path      = ENV["fzf_path"]    || `which fzf`.strip

fd_path = "/etc/profiles/per-user/brandon/bin/fd"
fzf_path = "/etc/profiles/per-user/brandon/bin/fzf"
###############################################################

memorize      = ENV["memorize"].to_i == 1 ? true : false

search_paths  = ENV["search_home"] || ENV["search_path"]
search_paths  = search_paths.split(/\s*;\s*/)
search_paths = search_paths.map do |search_path|
  path = File.expand_path(search_path)
  File.exist?(path) ? path : nil
end.compact.uniq

fd_options     = ENV["fd_options"]     || ""
num_candidates = ENV["num_candidates"] || "100"
num_candidates = num_candidates.to_i

keys = ARGV.join(" ").gsub("　", " ").split(/\s+/)
query = +""
keys.each do |key|
  if /\A(?:\^|\-)(?:d|dir|directory)\z/ =~ key
    fd_options = "-p -t d"
  elsif /\A(?:\^|\-)(?:f|file)\z/ =~ key
    fd_options = "-p -t f"
  else
    query << key + " "
  end
end

query.strip!

results = []

search_paths.each do |search_path|
  if /\A\/Users\/[^\/]+\z/ =~ search_path
    fd_options += " --exclude Library" 
  end
  results_all = `#{fd_path} . "#{search_path}" #{fd_options} 2> /dev/null | #{fzf_path} -e --filter="#{query}" --print0`
  results += results_all.split("\x00")[0...num_candidates]
end

items = []
type = "file:skipcheck"

if results.size > 0
  results.each do |result|
    path_split = result.split(File::SEPARATOR)
    title = File::SEPARATOR + path_split[-2 .. -1].join(File::SEPARATOR)
    subtitle = path_split[0 ... -2].join(File::SEPARATOR)
    item = {
      "valid": true,
      "type": type,
      "title": title,
      "subtitle": subtitle,
      "arg": result,
      "icon": {
        "type": "fileicon",
        "path": result
      }
    }
    if memorize
      # uid = Digest::MD5.hexdigest(result)
      item["uid"] = result
    end
    items << item
  end
  unless ENV["history_search"]
    prepend_line_to_file(history_file, "#{Time.new} | #{query}", max_search_history)
  end
else
  items << {
    "title": "No results found",
    "valid": false
  }
end

jsonout = {"items": items}.to_json 

print jsonout
```

**Comment by typkrft** [comment]
Hardcoding the paths doesn't seem, to have an effect. 
```logs
[10:44:37.268] fzf-alfred-workfow[Keyword] Processing complete
[10:44:37.282] fzf-alfred-workfow[Keyword] Passing output 'code' to Arg and Vars
[10:44:37.283] fzf-alfred-workfow[Arg and Vars] Processing complete
[10:44:37.284] fzf-alfred-workfow[Arg and Vars] Passing output 'code' to Junction
[10:44:37.285] fzf-alfred-workfow[Junction] Processing complete
[10:44:37.286] fzf-alfred-workfow[Junction] Passing output 'code' to Transform
[10:44:37.287] fzf-alfred-workfow[Transform] Processing complete
[10:44:37.287] fzf-alfred-workfow[Transform] Passing output 'code' to Script Filter
[10:44:37.292] fzf-alfred-workfow[Script Filter] Queuing argument 'code'
[10:44:37.455] fzf-alfred-workfow[Script Filter] Script with argv 'code' finished
[10:44:37.461] fzf-alfred-workfow[Script Filter] {"items":[{"title":"No results found","valid":false}]}
```

**Comment by yohasebe** [comment]
I'm not familiar with nix, but using it instead of Homebrew might be related to the problem.

In the Ruby code, the search is performed using `fd` and `fzf `through a system exec. If these commands were installed via nix, they might not be visible to it.

I'll continue to share any new ideas that come up, but for now, I think I've run out of them.

**Comment by typkrft** [comment]
> I'm not familiar with nix, but using it instead of Homebrew might be related to the problem.
> 
> In the Ruby code, the search is performed using `fd` and `fzf `through a system exec. If these commands were installed via nix, they might not be visible to it.
> 
> I'll continue to share any new ideas that come up, but for now, I think I've run out of them.

When I have some free time, I troubleshoot it. The script looks relatively simply, so I doubt there's anything wrong there.  There's two potential issues that I'm going to investigate. 1. Nix is downloading the fzf alfred workflow and unpacking it, because of the way nix works, this results in all the files being immutable. I did try installing manually, but maybe a dependency it needs is stuck unwritable. 2. Look into my environment. 

Thanks for the help. I'll report back if I can resolve it.

**Comment by typkrft** [comment]
My issue was resolved. I apologize as it's not particularly related to the thread. It seems to have something to do with nix making all files in its' store read only. I tried to get around this by excluding the info.plist and manually importing it, but it still didn't seem to work. Downloading and unzipping the plugin into Alfred's workflow folder resolved the issue for me.

**Comment by yohasebe** [comment]
That is great! I hope you enjoy the workflow!
